<?php

namespace App\Enums;

enum GroceryItemSource: string
{
    case AutoRecipe = 'auto_recipe';
    case AutoSimpleItem = 'auto_simple_item';
    case Manual = 'manual';
    case Repeater = 'repeater';

    public function label(): string
    {
        return match ($this) {
            self::AutoRecipe => 'From a recipe',
            self::AutoSimpleItem => 'From a simple item',
            self::Manual => 'Added manually',
            self::Repeater => 'Repeating item',
        };
    }

    /**
     * Auto-sourced lines are removed again if their component leaves the plan;
     * manual and repeater lines are the user's own and are left alone.
     */
    public function isAutoGenerated(): bool
    {
        return in_array($this, [self::AutoRecipe, self::AutoSimpleItem], true);
    }
}
